-- BASIC QUERIES
-- Unless otherwise stated, all queries should return all columns

-- Get all information about all authors
-- SELECT * FROM authors;
-- Get just the name and birth year of all authors
-- SELECT * FROM authors WHERE name IS NOT NULL AND birth_year IS NOT NULL;
-- Get all authors born in the 20th centruy or later
-- SELECT * FROM authors WHERE birth_year >= 2000;
-- Get all authors born in the USA
-- SELECT * FROM authors WHERE nationality= 'United States of America';
-- Get all books published on 1985
-- SELECT * FROM books WHERE publication_date = 1985 ;
-- Get all books published before 1989
-- SELECT * FROM books WHERE publication_date < 1989 ;
-- Get just the title of all books.
-- SELECT * FROM books WHERE title IS NOT NULL ;
-- Get just the year that 'A Dance with Dragons' was published
--   Cry when you realize how long it's been
-- SELECT * FROM books WHERE title = 'A Dance with Dragons' AND publication_date IS NOT NULL ;
-- Get all books which have `the` somewhere in their title (hint, look up LIKE/ILIKE)
-- SELECT * FROM books WHERE title LIKE '%the%';
-- Add yourself as an author
-- INSERT INTO authors (name ,nationality ,birth_year ) VALUES ('Wejdan Alrasheedi','Saudi Arabis', 1995 );
-- Add two books that you'd like to write (you can hard-code your id as the author id)
-- INSERT INTO books (title ,publication_date ,author_id) VALUES ('The end of 2017' , 2025 ,9);
-- INSERT INTO books (title ,publication_date ,author_id) VALUES ('Alone' , 2028 ,9);
-- Update one of your books to have a new title
-- UPDATE books SET title = 'The end both 2017 & 2018' WHERE id=70 ; 
-- Delete your books
-- DELETE FROM books WHERE id = 72 ;
-- DELETE FROM books WHERE id = 70 ;
-- Delete your author entry
-- DELETE FROM authors  WHERE id = 9 ;
